apiVersion: apps/v1
kind: Deployment
metadata:
  name: will-playground-deployment
  labels:
    app: will-playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: will-playground
  template:
    metadata:
      labels:
        app: will-playground
    spec:
      containers:
      - name: will-container
        image: wil42/playground:v2
        ports:
        - containerPort: 8888